# Patch for argocd-cm to enable GitHub SSO via bundled Dex.
# Replace GITHUB_CLIENT_ID and GITHUB_ORG with your values.
# Store the OAuth client secret in argocd-secret (see README).
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Argo CD base URL (must match how you reach the UI; used for OAuth callback)
  url: https://argocd-server-lb.argocd.local/
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: GITHUB_CLIENT_ID
        clientSecret: $dex.github.clientSecret
        orgs:
        - name: GITHUB_ORG
